# Generated by Django 5.1.6 on 2025-02-28 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loantransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loantransaction",
            name="is_successful",
        ),
        migrations.AddField(
            model_name="loan",
            name="amount_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="payment_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
