# Generated by Django 5.1.6 on 2025-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_remove_loantransaction_is_successful_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
