# Generated by Django 5.1.6 on 2025-03-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_alter_loan_amount_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
