# Generated by Django 5.1.6 on 2025-03-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loan_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="monthly_emi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
